name: Test k8s actions
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  test-microk8s:
    runs-on: ubuntu-latest
    name: Test MicroK8s
    steps:
    - uses: balchua/microk8s-actions@v0.2.2
      with:
        channel: 'latest/stable'
    - name: Test
      run: |
        set -ex
        kubectl get no
  test-k3d:
    runs-on: ubuntu-latest
    name: Test k3d 
    steps:
    - uses: AbsaOSS/k3d-action@v2
      name: "Create Single Cluster"
      with:
        cluster-name: "test-cluster-1"
        args: --agents 1
    - name: Test
      run: |
        set -ex
        kubectl get no
